// layout.tsx
import type { Metadata } from "next";
import { Poppins, Dancing_Script} from "next/font/google";
import "./globals.css";

const dancingScript = Dancing_Script({
  variable: '--font-dancingScript',
  subsets: ['latin'],
  weight: ['400', '500', '600', '700'],
});

const poppins = Poppins({
  variable: "--font-poppins",
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"],
});

export const metadata: Metadata = {
  title: ".GetFood",
  description: "Generated by create next app",
  themeColor: '#451a03',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pt-br" className={`${poppins.variable} ${dancingScript.variable}`}>
      <head>
        <meta name="apple-mobile-web-app-status-bar-style" content="black-translucent" />
        <meta name="msapplication-navbutton-color" content="#451a03" />
      </head>
      <body className="antialiased font-sans">
        {children}
      </body>
    </html>
  );
}
